env:
  TERM: alacritty

window:
  dimensions:
    columns: 100
    lines: 60

  position:
    x: 0
    y: 0

  padding:
    x: 0
    y: 0

  decorations: full
  startup_mode:  Maximized
  title: Alacritty
  dynamic_title: true
  class:
    instance: Alacritty
    general: Alacritty

scrolling:
  history: 10000
  multiplier: 3
font:
  normal:
    family: monospace
    style: Regular
  bold:
    family: monospace
    style: Bold
  italic:
    family: monospace
    style: Italic
  bold_italic:
    family: monospace
    style: Bold Italic
  size: 10

  offset:
    x: 0
    y: 0

  glyph_offset:
    x: 0
    y: 0

colors:
  # Default colors
  primary:
    background: '0x1e2127'
    foreground: '0xabb2bf'

  normal:
    black:   '0x1e2127'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0x828791'

  # Bright colors
  bright:
    black:   '0x5c6370'
    red:     '0xe06c75'
    green:   '0x98c379'
    yellow:  '0xd19a66'
    blue:    '0x61afef'
    magenta: '0xc678dd'
    cyan:    '0x56b6c2'
    white:   '0xe6efff'


  # primary:
  #   background: '0x1b182c'
  #   foreground: '0xcbe3e7'
  #
  # normal:
  #   black:   '0x100e23'
  #   red:     '0xff8080'
  #   green:   '0x95ffa4'
  #   yellow:  '0xffe9aa'
  #   blue:    '0x91ddff'
  #   magenta: '0xc991e1'
  #   cyan:    '0xaaffe4'
  #   white:   '0xcbe3e7'
  #
  # bright:
  #   black:   '0x565575'
  #   red:     '0xff5458'
  #   green:   '0x62d196'
  #   yellow:  '0xffb378'
  #   blue:    '0x65b2ff'
  #   magenta: '0x906cff'
  #   cyan:    '0x63f2f1'
  #   white:   '0xa6b3cc'
  #
  cursor:
    text: CellBackground
    cursor: CellForeground

  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground

  line_indicator:
    foreground: None
    background: None
  indexed_colors: []
background_opacity: 1.0
selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>\t"
  save_to_clipboard: true

cursor:
  style:
    shape: Block
    blinking: Off

  vi_mode_style: None
  blink_interval: 750
  unfocused_hollow: true
  thickness: 0.15

working_directory: None
alt_send_esc: true

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
